### ISSUE TITLE
Allow to retrieve unseen transactions only

### ISSUE THREAD

**Issue by triceo** [zonkyio/zonky-api#12]
I would like to be able to find out all the transactions in a user's wallet, but only those I have not seen yet. I can see that happening in two ways:

- I query on the transaction date. Unfortunately, that doesn't help me, as transactions always say midnight. Some transactions also show up on day X, but are actually posted with a date Y, several days in the past.
- So I need to query on the ID, as in "give me all transactions with ID > X", where X is the last transaction previously seen. This is currently not possible in the API. 

Queyring by the ID makes the most sense to me, and I would appreciate if you could make it work.

(As a side note, I have been asked by Petr Vlcek to create this issue here.)

**Comment by lukasnovy** [comment]
Cleaning old tickets. Transactions are not available in public API any more.
