### ISSUE TITLE
Configurable OAuth token expiration

### ISSUE THREAD

**Issue by triceo** [zonkyio/zonky-api#2]
During today's Zonky evening in Brno, a suggestion was made to make the OAuth token expiration configurable, instead of the seemingly hard-coded 300 seconds.
- The arguments for this seem to be that users get more flexibility and the servers get less load for authenticating and refreshing. 
- The argument against this is security - increasing the expiration period exposes the token for a longer period of time. 
- In this case, however, this feature could work both ways - people could also configure the refresh interval to be less than standard, not just more.

**Comment by lukasnovy** [comment]
This issue has been resolved with mandatory 2FA authorization. Oauth clients can specify expiration time during client registration to zonky system
