### ISSUE TITLE
Filter rating__in does not work for secondary marketplace

### ISSUE THREAD

**Issue by vojtechkubin** [zonkyio/zonky-api#35]
Hello,

I've tried filtering by rating__in with various inputs in secondary marketplace, but none of them worked:

- `rating__in=["A","B"]`
- `rating__in=[A,B]`
- `rating__in=A&rating_in=B`
- `rating__in=A`

Is this a bug in the API or am I missing something?
Thank you in advance.

**Comment by lukasnovy** [comment]
Hi,
filter is working corretly. First option is valid, but you must http encode illegal characters. 
For example this is valid request:
[https://app.zonky.cz/api/smp/investments?rating__in=%5B%22AA%22%2C%22B%22%2C%22C%22%5D](https://app.zonky.cz/api/smp/investments?rating__in=%5B%22AA%22%2C%22B%22%2C%22C%22%5D)
